In [43]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [44]:
df=pd.read_csv("Zomato Dataset.csv")

In [45]:
print("shape:",df.shape)
print("FINDING NULL VALUES\n",df.isnull().sum())

shape: (45584, 20)
FINDING NULL VALUES
 ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45584 non-null  str
 1   Delivery_person_ID           45584 non-null  str
 2   Delivery_person_Age          43730 non-null  float64
 3   Delivery_person_Ratings      43676 non-null  float64
 4   Restaurant_latitude          45584 non-null  float64
 5   Restaurant_longitude         45584 non-null  float64
 6   Delivery_location_latitude   45584 non-null  float64
 7   Delivery_location_longitude  45584 non-null  float64
 8   Order_Date                   45584 non-null  str
 9   Time_Orderd                  43853 non-null  str
 10  Time_Order_picked            45584 non-null  str
 11  Weather_conditions           44968 non-null  str
 12  Road_traffic_density         44983 non-null  str
 13  Vehicle_condition            45584 non-null  int64
 14  Type_of_order                45584 non-null  str
 15  Type_of_vehicle              45584 non-null  str
 16  multiple_deliveries          44591 non-null  float64
 17  Festival                     45356 non-null  str
 18  City                         44384 non-null  str
 19  Time_taken (min)             45584 non-null  int64
dtypes: float64(7), int64(2), str(11)
memory usage: 10.3 MB

In [47]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Delivery_person_Age,43730.0,29.566911,5.815064,15.000000,25.000000,30.000000,35.000000,50.000000
Delivery_person_Ratings,43676.0,4.633774,0.334744,1.000000,4.500000,4.700000,4.900000,6.000000
Restaurant_latitude,45584.0,17.017948,8.185674,-30.905562,12.933284,18.551440,22.728163,30.914057
Restaurant_longitude,45584.0,70.229684,22.885575,-88.366217,73.170000,75.897963,78.044095,88.433452
Delivery_location_latitude,45584.0,17.465480,7.335562,0.010000,12.988453,18.633934,22.785049,31.054057
Delivery_location_longitude,45584.0,70.844161,21.120578,0.010000,73.280000,76.002574,78.107044,88.563452
Vehicle_condition,45584.0,1.023385,0.839055,0.000000,0.000000,1.000000,2.000000,3.000000
multiple_deliveries,44591.0,0.744635,0.572510,0.000000,0.000000,1.000000,1.000000,3.000000
Time_taken (min),45584.0,26.293963,9.384298,10.000000,19.000000,26.000000,32.000000,54.000000

In [49]:
print(df.duplicated().sum())

0

In [50]:
pd.DataFrame({"missing count":df.isnull().sum()})

                             missing count
ID                                       0
Delivery_person_ID                       0
Delivery_person_Age                   1854
Delivery_person_Ratings               1908
Restaurant_latitude                      0
Restaurant_longitude                     0
Delivery_location_latitude               0
Delivery_location_longitude              0
Order_Date                               0
Time_Orderd                           1731
Time_Order_picked                        0
Weather_conditions                     616
Road_traffic_density                   601
Vehicle_condition                        0
Type_of_order                            0
Type_of_vehicle                          0
multiple_deliveries                    993
Festival                               228
City                                  1200
Time_taken (min)                         0

In [51]:
df.dropna(subset=["Time_Orderd"],inplace=True)
print(df["Festival"].value_counts(dropna=False))
print(df['City'].value_counts(dropna=False))
df.isnull().sum()

Festival
No     42777
Yes      857
NaN      219
Name: count, dtype: int64
City
Metropolitian    32796
Urban             9757
NaN               1144
Semi-Urban         156
Name: count, dtype: int64

ID                                0
Delivery_person_ID                0
Delivery_person_Age             214
Delivery_person_Ratings         268
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                       0
Time_Order_picked                 0
Weather_conditions                0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             943
Festival                        219
City                           1144
Time_taken (min)                  0
dtype: int64

In [52]:
df['City']=df['City'].replace('NaN', np.nan)
df['Festival']=df['Festival'].replace('NaN', np.nan)
df['City']=df['City'].fillna(df['City'].mode())
df['Festival']=df['Festival'].fillna(df['Festival'].mode().iloc[0])
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age             214
Delivery_person_Ratings         268
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                       0
Time_Order_picked                 0
Weather_conditions                0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             943
Festival                          0
City                           1144
Time_taken (min)                  0
dtype: int64

In [53]:
df['Delivery_person_Age'] = (df['Delivery_person_Age'].fillna(df['Delivery_person_Age'].mean()))
df['multiple_deliveries'] = df['multiple_deliveries'].fillna(df['multiple_deliveries'].mode().iloc[0])
df['Delivery_person_Ratings']=df['Delivery_person_Ratings'].fillna(df['Delivery_person_Ratings'].mean())
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age               0
Delivery_person_Ratings           0
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                       0
Time_Order_picked                 0
Weather_conditions                0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                           1144
Time_taken (min)                  0
dtype: int64

In [54]:
numerical_cols=df[['Delivery_person_Age','Delivery_person_Ratings','Restaurant_latitude','Restaurant_longitude','Delivery_location_latitude','Delivery_location_longitude',	'Vehicle_condition','multiple_deliveries','Time_taken (min)']]
numerical_cols.corr()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition,multiple_deliveries,Time_taken (min)
Delivery_person_Age,1.000000,-0.117517,0.001400,0.000077,0.002448,0.000074,-0.001936,0.115140,0.303037
Delivery_person_Ratings,-0.117517,1.000000,-0.012051,-0.013448,-0.013505,-0.013635,0.048777,-0.123870,-0.359836
Restaurant_latitude,0.001400,-0.012051,1.000000,0.650109,0.935340,0.650162,-0.001751,0.007633,0.015243
Restaurant_longitude,0.000077,-0.013448,0.650109,1.000000,0.690755,0.999998,-0.003807,0.003874,0.008073
Delivery_location_latitude,0.002448,-0.013505,0.935340,0.690755,1.000000,0.690817,-0.000711,0.008468,0.014815
Delivery_location_longitude,0.000074,-0.013635,0.650162,0.999998,0.690817,1.000000,-0.003794,0.004089,0.008631
Vehicle_condition,-0.001936,0.048777,-0.001751,-0.003807,-0.000711,-0.003794,1.000000,-0.100712,-0.243176
multiple_deliveries,0.115140,-0.123870,0.007633,0.003874,0.008468,0.004089,-0.100712,1.000000,0.379195
Time_taken (min),0.303037,-0.359836,0.015243,0.008073,0.014815,0.008631,-0.243176,0.379195,1.000000

In [55]:
df['is_delayed']=None
#print(df.head(5))
df.isnull().sum()

ID                                 0
Delivery_person_ID                 0
Delivery_person_Age                0
Delivery_person_Ratings            0
Restaurant_latitude                0
Restaurant_longitude               0
Delivery_location_latitude         0
Delivery_location_longitude        0
Order_Date                         0
Time_Orderd                        0
Time_Order_picked                  0
Weather_conditions                 0
Road_traffic_density               0
Vehicle_condition                  0
Type_of_order                      0
Type_of_vehicle                    0
multiple_deliveries                0
Festival                           0
City                            1144
Time_taken (min)                   0
is_delayed                     43853
dtype: int64

In [56]:
df['is_delayed'] = (df['Time_taken (min)'] >=30).astype(int)
#print(df.head(5))
print(df["is_delayed"])

0        1
1        0
2        0
3        0
4        1
        ..
45579    1
45580    1
45581    0
45582    0
45583    1
Name: is_delayed, Length: 43853, dtype: int64

In [57]:

feature_cols = [
    'Delivery_person_Age',
    'Delivery_person_Ratings',
    'Weather_conditions',
    'Road_traffic_density',
    'Vehicle_condition',
    'Type_of_vehicle',
    'multiple_deliveries',
    'Festival',
    'City',
]
df_clean = df[feature_cols + ['is_delayed']].dropna()
print(df_clean.head(10))
print("*"*60,"\n")
df_encoded = pd.get_dummies(df_clean,drop_first=True)
print(df_encoded.head(5))

   Delivery_person_Age  Delivery_person_Ratings Weather_conditions  \
0                 36.0                      4.2                Fog
1                 21.0                      4.7             Stormy
2                 23.0                      4.7         Sandstorms
3                 34.0                      4.3         Sandstorms
4                 24.0                      4.7                Fog
5                 29.0                      4.5         Sandstorms
6                 35.0                      4.0              Windy
7                 33.0                      4.2         Sandstorms
8                 34.0                      4.9             Cloudy
9                 21.0                      4.7              Windy

  Road_traffic_density  Vehicle_condition   Type_of_vehicle  \
0                  Jam                  2        motorcycle
1                 High                  1        motorcycle
2               Medium                  1           scooter
3                  Low                  0        motorcycle
4                  Jam                  1           scooter
5                  Jam                  2  electric_scooter
6                 High                  1           scooter
7                  Jam                  2        motorcycle
8                  Jam                  0        motorcycle
9                  Jam                  0        motorcycle

   multiple_deliveries Festival           City  is_delayed
0                  3.0       No  Metropolitian           1
1                  1.0       No  Metropolitian           0
2                  1.0       No  Metropolitian           0
3                  0.0       No  Metropolitian           0
4                  1.0       No  Metropolitian           1
5                  1.0       No  Metropolitian           0
6                  1.0       No  Metropolitian           1
7                  1.0       No  Metropolitian           1
8                  1.0       No  Metropolitian           1
9                  1.0       No          Urban           0
************************************************************

   Delivery_person_Age  Delivery_person_Ratings  Vehicle_condition  \
0                 36.0                      4.2                  2
1                 21.0                      4.7                  1
2                 23.0                      4.7                  1
3                 34.0                      4.3                  0
4                 24.0                      4.7                  1

   multiple_deliveries  is_delayed  Weather_conditions_Fog  \
0                  3.0           1                    True
1                  1.0           0                   False
2                  1.0           0                   False
3                  0.0           0                   False
4                  1.0           1                    True

   Weather_conditions_Sandstorms  Weather_conditions_Stormy  \
0                          False                      False
1                          False                       True
2                           True                      False
3                           True                      False
4                          False                      False

   Weather_conditions_Sunny  Weather_conditions_Windy  \
0                     False                     False
1                     False                     False
2                     False                     False
3                     False                     False
4                     False                     False

   Road_traffic_density_Jam  Road_traffic_density_Low  \
0                      True                     False
1                     False                     False
2                     False                     False
3                     False                      True
4                      True                     False

   Road_traffic_density_Medium  Type_of_vehicle_motorcycle  \
0                        False                        True
1                        False                        True
2                         True                       False
3                        False                        True
4                        False                       False

   Type_of_vehicle_scooter  Festival_Yes  City_Semi-Urban  City_Urban
0                    False         False            False       False
1                    False         False            False       False
2                     True         False            False       False
3                    False         False            False       False
4                     True         False            False       False

In [58]:
X = df_encoded.drop('is_delayed', axis=1)
y = df_encoded['is_delayed']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [59]:
#Using RandomForestClassifier from Scikit-learn
model = RandomForestClassifier(n_estimators=100, random_state=42)

# 2. Fit the model on training data
model.fit(X_train, y_train)

# 3. Predict on test data
y_pred = model.predict(X_test)

In [60]:
#using if else
'''# Create comparison table matching the project format
tested_df = pd.DataFrame({
    'Actual Status': ['Delayed' if y == 1 else 'Not Delayed' for y in y_test],
    'Predicted Status': ['Delayed' if y == 1 else 'Not Delayed' for y in y_pred]
})

# Display the comparison side-by-side
print(tested_df.head(10).to_string(index=False))'''

# uing map 

results_comparison = pd.DataFrame({'Actual': y_test.values, 'Predicted': y_pred})

results_comparison['Actual Status'] = results_comparison['Actual'].map({0: 'Not Delayed', 1: 'Delayed'})

results_comparison['Predicted Status'] = results_comparison['Predicted'].map({0: 'Not Delayed', 1: 'Delayed'})
print(results_comparison.head(5))

   Actual  Predicted Actual Status Predicted Status
0       0          0   Not Delayed      Not Delayed
1       1          1       Delayed          Delayed
2       0          1   Not Delayed          Delayed
3       1          1       Delayed          Delayed
4       0          0   Not Delayed      Not Delayed

In [61]:
accuracy = accuracy_score(y_test, y_pred) * 100

print("Model Accuracy:",accuracy)

Model Accuracy: 87.11074689768205